#!/bin/sh

FILEOUT=$1
EFF=$2
FRAC=$3
ACC=$4

./simulate.exe --settings=\
numberOfCyclists=20e6,\
helmetEffectiveness=$EFF,\
helmetWearingFraction=$FRAC,\
probOfCrashing[0]=0.01,\
probOfCrashing[1]=0.01,\
probFatalHeadInjury[0]=0.0003,\
probFatalHeadInjury[1]=0.0003,\
probFatalOtherInjury[0]=0.0005,\
probFatalOtherInjury[1]=0.0005,\
coronerAccuracy=$ACC,\
numIterations=10000,\
seed=0 > $FILEOUT

