#!/bin/sh

simulate.exe --settings=\
numberOfCyclists=4e6,\
helmetEffectiveness=0.3,\
helmetWearingFraction=0.35,\
probOfCrashing[0]=0.01,\
probOfCrashing[1]=0.01,\
probFatalHeadInjury[0]=0.001,\
probFatalHeadInjury[1]=0.001,\
probFatalOtherInjury[0]=0.001,\
probFatalOtherInjury[1]=0.001,\
coronerAccuracy=0.9,\
numIterations=5000,\
seed=0

